# fpga4student.com: FPGA projects, Verilog projects, VHDL projects
# FPGA tutorial: How to interface a mouse with Basys 3 FPGA 
# Verilog code for interfacing a mouse with the Basys 3 FPGA board  
##USB HID (PS/2)
 set_property PACKAGE_PIN C17 [get_ports mouse_clk]                        
     set_property IOSTANDARD LVCMOS33 [get_ports mouse_clk]
     set_property PULLUP true [get_ports mouse_clk]
 set_property PACKAGE_PIN B17 [get_ports mouse_ps2]                    
     set_property IOSTANDARD LVCMOS33 [get_ports mouse_ps2]    
     set_property PULLUP true [get_ports mouse_ps2]
# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]       
 set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN R2 [get_ports reset]     
 #set_property IOSTANDARD LVCMOS33 [get_ports reset]
#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports {cath[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[6]}]
set_property PACKAGE_PIN W6 [get_ports {cath[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[5]}]
set_property PACKAGE_PIN U8 [get_ports {cath[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[4]}]
set_property PACKAGE_PIN V8 [get_ports {cath[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[3]}]
set_property PACKAGE_PIN U5 [get_ports {cath[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[2]}]
set_property PACKAGE_PIN V5 [get_ports {cath[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[1]}]
set_property PACKAGE_PIN U7 [get_ports {cath[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {cath[0]}]
set_property PACKAGE_PIN U2 [get_ports {anod[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {anod[0]}]
set_property PACKAGE_PIN U4 [get_ports {anod[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {anod[1]}]
set_property PACKAGE_PIN V4 [get_ports {anod[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {anod[2]}]
set_property PACKAGE_PIN W4 [get_ports {anod[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {anod[3]}]
   
set_property PACKAGE_PIN U18 [get_ports restart]						
       set_property IOSTANDARD LVCMOS33 [get_ports restart]
set_property PACKAGE_PIN T18 [get_ports start1]                        
       set_property IOSTANDARD LVCMOS33 [get_ports start1]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property PACKAGE_PIN V3 [get_ports {leds[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property PACKAGE_PIN W3 [get_ports {leds[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property PACKAGE_PIN U3 [get_ports {leds[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property PACKAGE_PIN P3 [get_ports {leds[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
set_property PACKAGE_PIN N3 [get_ports {leds[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
set_property PACKAGE_PIN P1 [get_ports {leds[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
set_property PACKAGE_PIN L1 [get_ports {leds[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]